### ISSUE TITLE
No way to set routerID to podIP using kube-vip Chart

### ISSUE THREAD

**Issue by interdependence** [kube-vip/helm-charts#17]
According to the [docs](https://kube-vip.io/docs/installation/daemonset/#managing-a-routerid-as-a-daemonset) it is recommended to use the podIP as `bgp_routerid`:

```yaml
- name: bgp_routerid
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
```

Unfortunately due to the way env values are templated, it doesn't seem possible to set a `valueFrom` key when deploying kube-vip using helm.
