### ISSUE TITLE
Let to configure command line args

### ISSUE THREAD

**Issue by angeloxx** [kube-vip/helm-charts#33]
In a scenario with multiple running KubeVIP we have to customize the Prometheus HTTP listener with the parameter --prometheusHTTPServer. The Helm chart doesn't allow to specify extraArgs to the application.

Sample Yaml configuration:

```
    spec:
      containers:
      - args:
        - manager
        - --prometheusHTTPServer=0.0.0.0:2113
```
