### ISSUE TITLE
helm templating for extArguments inCluster

### ISSUE THREAD

**Issue by eldeeishere** [kube-vip/helm-charts#63]
# [Bug] Kube-VIP Helm Chart Templating Issue with `inCluster` Value

## Description

When templating the Kube-VIP Helm chart with the `inCluster` value, the generated manifest incorrectly includes the `--inCluster` flag in the container arguments. This leads to an error in the Kube-VIP manager pod logs:

​```
Error: unknown flag: --inCluster
Usage: kube-vip manager [flags]
​```

## Expected Behavior

The Kube-VIP Helm chart should correctly template the `inCluster` value in the container arguments. The expected output for the `inCluster` value should be:

```yaml
  spec:
    containers:
      - args:
          - manager
          - inCluster
          - --servicesElection
```

## Current Behavior

The current templating of the `inCluster` value in the Kube-VIP Helm chart results in the following incorrect output:

```yaml
  spec:
    containers:
      - args:
          - manager
          - --inCluster
          - --servicesElection
```

## Steps to Reproduce

1. Install the Kube-VIP Helm chart with the `inCluster` value set.

```yaml
  extraArgs:
    inCluster: null
    servicesElection: null
```

2. Check the generated manifest for the Kube-VIP manager deployment.
3. Observe that the `inCluster` value is incorrectly templated as `--inCluster` in the container arguments.

## Additional Information

- Helm Chart Version: [0.6.6]
- Kubernetes Version: [1.31.0]
- KubeVip image:  0.8.9

## Possible Solution

Update the Kube-VIP Helm chart template to correctly handle the `inCluster` value in the container arguments. Ensure that the `inCluster` value is templated without the leading `--` when included in the container arguments.

## Impact

This templating issue prevents the Kube-VIP manager from starting correctly, as it encounters an unknown flag error. Fixing this issue will ensure that the Kube-VIP manager can start and function as expected when the `inCluster` value is set.

**Comment by eldeeishere** [comment]
Lets user decide about --

i woude change DS it to 

```yaml
          {{- if kindIs "map" .Values.extraArgs }}
          {{- range $key, $value := .Values.extraArgs }}
          - {{ $key }}{{ if not (eq $value nil) }}={{ tpl ($value | toString) $ }}{{ end }}
          {{- end }}
          {{- end }}
```

and let user define flags like this

```yaml
    spec:
      containers:
      - args:
        - manager
        - --servicesElection
        - inCluster
```
